name: bb_voice_transcription
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - pip:
    - faster_whisper
    - nemo_toolkit[asr]
    - pydub
    - torch
    - scikit-learn
    - numpy
    - librosa